/* generated by dia/codegen.py */
class UFERSAOS 
{
public:
	 comunicarProcesso ();
	 criarProcesso ();
	 escalonar ();
	 gerenciarMemoria ();
	 gerenciarProcessos ();
	 gerenciarArquivos ();
	 terminarProcesso ();
	 tratarInterrupcao ();
	 verProcesso ();
	 processos;
	 memoria;
	 arquivos;
};

